In [ ]:
import numpy as np
from scipy.optimize import linprog

# Define the objective function coefficients
c = np.array([1, 0, 0, ..., 0])

# Define the inequality constraints matrix
T = np.array([[T_11, T_12, ..., T_1n],
              [T_21, T_22, ..., T_2n],
              ...
              [T_m1, T_m2, ..., T_mn]])

# Define the inequality constraints vector
xi_i = np.array([xi_1, xi_2, ..., xi_m])

# Define the inequality constraints bounds
bounds = [(0, None)] * n

# Define the equality constraints matrix
A_eq = np.array([[sigma_1, sigma_2, ..., sigma_n]])

# Define the equality constraints vector
b_eq = np.array([n * epsilon])

# Solve the linear programming problem
res = linprog(c, A_ub=-T, b_ub=-xi_i, A_eq=A_eq, b_eq=b_eq, bounds=bounds, method='highs')

# Extract the solution
z = res.x

# Print the solution
print("Optimal solution:")
print(z)


In [ ]:
import numpy as np
from scipy.optimize import linprog

# 目的関数の係数を定義
c = np.array([1, 0, 0, ..., 0])

# 不等式制約の行列を定義
T = np.array([[T_11, T_12, ..., T_1n],
              [T_21, T_22, ..., T_2n],
              ...
              [T_m1, T_m2, ..., T_mn]])

# 不等式制約のベクトルを定義
xi_i = np.array([xi_1, xi_2, ..., xi_m])

# 不等式制約の上下限を定義
bounds = [(0, None)] * n

# 等式制約の行列を定義
A_eq = np.array([[sigma_1, sigma_2, ..., sigma_n]])

# 等式制約のベクトルを定義
b_eq = np.array([n * epsilon])

# 線形計画問題を解く
res = linprog(c, A_ub=-T, b_ub=-xi_i, A_eq=A_eq, b_eq=b_eq, bounds=bounds, method='highs')

# 解を抽出
z = res.x

# 解を表示
print("最適解:")
print(z)


In [26]:
import numpy as np
np.random.seed(0)
xi = []
for _ in range(5):
    mean = np.random.uniform(0, 10, 5)  # 平均ベクトルをランダムに生成
    variance = np.random.uniform(1, 5, 5)  # 分散ベクトルをランダムに生成
    consumer_demand = np.abs(np.random.normal(mean, np.sqrt(variance), 5))  # 正規分布に従うランダムベクトルを生成
    xi.append(consumer_demand)
    print(consumer_demand)

[5.76081437 9.5636864  7.65402889 5.71692171 4.94308096]
[10.41573095  9.07589781  2.99240736 11.79347301  1.18865138]
[2.56311785 8.0537746  5.47886704 5.58077858 8.26943708]
[ 3.88055565  2.68405536 10.43269923  0.15580677  0.428435  ]
[7.13446078 0.16747399 7.13596405 0.24574849 8.89003658]


In [6]:
sorted_xi = sorted(xi, key=lambda x: np.sum(x), reverse=True)
print(sorted_xi)

[array([10.41573095,  9.07589781,  2.99240736, 11.79347301,  1.18865138]), array([5.76081437, 9.5636864 , 7.65402889, 5.71692171, 4.94308096]), array([2.56311785, 8.0537746 , 5.47886704, 5.58077858, 8.26943708]), array([7.13446078, 0.16747399, 7.13596405, 0.24574849, 8.89003658]), array([ 3.88055565,  2.68405536, 10.43269923,  0.15580677,  0.428435  ])]


In [8]:
for i in sorted_xi:
    print(i)

[10.41573095  9.07589781  2.99240736 11.79347301  1.18865138]
[5.76081437 9.5636864  7.65402889 5.71692171 4.94308096]
[2.56311785 8.0537746  5.47886704 5.58077858 8.26943708]
[7.13446078 0.16747399 7.13596405 0.24574849 8.89003658]
[ 3.88055565  2.68405536 10.43269923  0.15580677  0.428435  ]


In [ ]:
import numpy as np

# 行列から二行ベクトルを取得
row1 = xi[0]
row2 = xi[1]

# ２行ベクトルの各要素の大きさを比較し、大きい場合はインデックスを先にする




In [11]:
K = 40
J = 100
C = np.random.uniform(10, 50, size=(K, J))

# C^TCの最大固有値を求める
eigenvalues = np.linalg.eigvals(C.T @ C)
max_eigenvalue = np.max(eigenvalues)
print(max_eigenvalue)


(3540292.729446726+0j)


In [13]:
print(xi)
for i in xi:
    print(i[0])

[array([5.76081437, 9.5636864 , 7.65402889, 5.71692171, 4.94308096]), array([10.41573095,  9.07589781,  2.99240736, 11.79347301,  1.18865138]), array([2.56311785, 8.0537746 , 5.47886704, 5.58077858, 8.26943708]), array([ 3.88055565,  2.68405536, 10.43269923,  0.15580677,  0.428435  ]), array([7.13446078, 0.16747399, 7.13596405, 0.24574849, 8.89003658])]
5.760814368534249
10.415730949159121
2.5631178512548636
3.88055565331742
7.134460783759826


In [15]:
# xiの第一成分で大きさを比較しソート
sorted_xi = sorted(xi, key=lambda x: x[0], reverse=True)
print(sorted_xi)

[array([10.41573095,  9.07589781,  2.99240736, 11.79347301,  1.18865138]), array([7.13446078, 0.16747399, 7.13596405, 0.24574849, 8.89003658]), array([5.76081437, 9.5636864 , 7.65402889, 5.71692171, 4.94308096]), array([ 3.88055565,  2.68405536, 10.43269923,  0.15580677,  0.428435  ]), array([2.56311785, 8.0537746 , 5.47886704, 5.58077858, 8.26943708])]


In [16]:
# sorted_xiの第一成分だけの配列にする
sorted_xi_1 = [i[0] for i in sorted_xi]
print(sorted_xi_1)

[10.415730949159121, 7.134460783759826, 5.760814368534249, 3.88055565331742, 2.5631178512548636]


In [17]:
print(xi)

[array([10.41573095,  9.07589781,  2.99240736, 11.79347301,  1.18865138]), array([7.13446078, 0.16747399, 7.13596405, 0.24574849, 8.89003658]), array([5.76081437, 9.5636864 , 7.65402889, 5.71692171, 4.94308096]), array([ 3.88055565,  2.68405536, 10.43269923,  0.15580677,  0.428435  ]), array([2.56311785, 8.0537746 , 5.47886704, 5.58077858, 8.26943708])]


In [19]:
#xiの列ごとにソート、要素を入れ替える
xi = np.array(xi)
print(xi)

[[10.41573095  9.07589781  2.99240736 11.79347301  1.18865138]
 [ 7.13446078  0.16747399  7.13596405  0.24574849  8.89003658]
 [ 5.76081437  9.5636864   7.65402889  5.71692171  4.94308096]
 [ 3.88055565  2.68405536 10.43269923  0.15580677  0.428435  ]
 [ 2.56311785  8.0537746   5.47886704  5.58077858  8.26943708]]


In [27]:
# 2次元配列を列成分で降順にソート
s_xi = np.sort(xi, axis=0)[::-1]
print(s_xi)

[[10.41573095  9.5636864  10.43269923 11.79347301  8.89003658]
 [ 7.13446078  9.07589781  7.65402889  5.71692171  8.26943708]
 [ 5.76081437  8.0537746   7.13596405  5.58077858  4.94308096]
 [ 3.88055565  2.68405536  5.47886704  0.24574849  1.18865138]
 [ 2.56311785  0.16747399  2.99240736  0.15580677  0.428435  ]]


In [ ]:
# 2次元配列の１行目が一番大きい値が入るようにスワップ
